//<!-- create student registration page -->
// <!-- firstname, lastname, email address, matricno(autogenerated), Courses, gender(male,female)
//display the informtion using a table -->
//    <!-- left -->

randomMatric = Math.floor(10000 + Math.random() * 9999);
  matricNo = document.getElementById("matricno");
  matric = "20" + randomMatric;
function generateMatric() {
  
  matricNo.innerHTML = matric;
}

const studentInfos = [];

function addStudent() {
  const firstname = document.getElementById("firstname").value;
  const lastname = document.getElementById("lastname").value;
  const name = `${lastname} ${firstname}`;
  const email = document.getElementById("email").value;
  const gender = document.getElementById("gender").value;
  const matricno = matric;
  const course1 = document.getElementById("course1").value;
  const course2 = document.getElementById("course3").value;
  const course3 = document.getElementById("course3").value;
  const course4 = document.getElementById("course4").value;
  const courses = `${course1} ${course2} ${course3} ${course4}`;

  const studentInfo = {
    name,
    email,
    gender,
    matricno,
    courses,
  };
if (firstname == "" || lastname == '' || email == "" || matricno == "" || course1 == "" || course2 == "" || course3 == ""|| course4 == "" || gender == "--select gender --" ){
    alert("Fill all input fields")
}else{
  studentInfos.push(studentInfo);
  console.log(studentInfos);
  display()
}
}

function display() {
 let displayStudents = document.getElementById("displayStudents");
    displayStudents.innerHTML ='';

    let table = document.createElement("table")
    table.className = "table table-striped"
    let header = document.createElement("tr")
    header.innerHTML = `
                <th>S/N</th>
                <th>Name</th>
                <th>E-mail Address</th>
                <th>Gender</th>
                <th>Matric No</th>
                <th>Courses</th>
                <th>Actions</th>

            `
    table.appendChild(header)
    

  for(i=0; i < studentInfos.length; i++){
    let row = document.createElement ("tr");
    row.innerHTML = `
    <td>${i+1}</td>
    <td>${studentInfos[i].name}</td>
    <td>${studentInfos[i].email}</td>
    <td>${studentInfos[i].gender}</td>
    <td>${studentInfos[i].matricno}</td>
    <td>${studentInfos[i].courses}</td>
    <td><img src="material-symbols--delete-rounded.svg" alt="" style='cursor:pointer;' onclick="deleteStudent(${i})" /></td>
`;
    table.appendChild(row);
  }
  
  displayStudents.appendChild(table);
  
}

function deleteStudent(val) {
    studentInfos.splice(val,1)
    display()
}
function clearfield(){

    firstname.value= ""
    lastname.value = ""
    email.value = ""
    gender.value = "--select gender--"
    matricNo.innerHTML =""
    course1.value = ""
    course2.value = ""
    course3.value = ""
    course4.value = ""
}